### ISSUE TITLE
RuntimeError: The size of tensor a does not match tensor b

### ISSUE THREAD

**Issue by keith-nlp** [ZNLP/NCLS-Corpora#5]
Hello, 

To start with, I am trying to train ZH2ENG with `beaver-base`.  But, I came across with a problem ` RuntimeError: The size of tensor a (5117) must match the size of tensor b (5000) at non-singleton dimension 1`, as shown below. 
I tried to fix it by adjusting training parameters e.g. batch size etc. It didn't work.

I would like to know if you have any clues about what I may do wrong here or what I should look for specifically.

Thank you.

```
2020-06-30 05:06:19,989 - Build dataset...
2020-06-30 05:07:28,283 - Build model...
2020-06-30 05:07:33,289 - start training...
2020-06-30 05:15:28,396 - step:     100 loss: 11.355503
Traceback (most recent call last):
  File "/home/zh2eng/code/beaver-base/train.py", line 97, in <module>
    main()
  File "/home/zh2eng/code/beaver-base/train.py", line 93, in main
    train(model, criterion, optimizer, train_dataset, valid_dataset)
  File "/home/zh2eng/code/beaver-base/train.py", line 55, in train
    scores = model(batch.src, batch.tgt)
  File "/home/jzliu/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zh2eng/code/beaver-base/beaver/model/nmt_model.py", line 43, in forward
    enc_out = self.encoder(src, src_pad)
  File "/home/jzliu/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zh2eng/code/beaver-base/beaver/model/transformer.py", line 62, in forward
    output = self.embedding(src)
  File "/home/jzliu/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zh2eng/code/beaver-base/beaver/model/embeddings.py", line 39, in forward
    embedding = self.embedding(x) * math.sqrt(self.embedding_dim) + self.pe[timestep:timestep + x.size(1)]
RuntimeError: The size of tensor a (5117) must match the size of tensor b (5000) at non-singleton dimension 1
```

**Comment by Zhujunnan** [comment]
Hi,

I think this error should be caused by some samples missing source documents or target summaries, which you can fix by filtering these sample. You should also locate specific errors through the pdb tool. 

Regards.

**Comment by MollyShuu** [comment]
in "embeddings.py", function positional_encoding(dim, max_len=5000),
the length of positional_encoding is limited to 5000, while the length of some news is larger than 5000. That's the point.
I occur this error as well, so I hope this answer can help you!
